........................................................................................F.F............E..........FE.....FFF....................
======================================================================
ERROR: test_search_arg_function_scalar_binop_scalar (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1310, in test_search_arg_function_scalar_binop_scalar
    self.assertEqual(search("sum(@) / 4", [1, 3]), 1.0)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 772, in search
    return resval(obj)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 294, in <lambda>
    out = cur_json(lambda obj: binop_json_scalar(binop, aval(obj), bval))
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 275, in binop_json_scalar
    return [func(v, s) for v in j]
TypeError: 'int' object is not iterable

======================================================================
ERROR: test_search_dot_parens_idx (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1415, in test_search_dot_parens_idx
    self.assertEqual(search("(@.foo)[0]", {'foo': [1,2], 'bar': 'a'}), 1)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 772, in search
    return resval(obj)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 577, in <lambda>
    result = lambda obj: apply_indexer_list(idxrs)(obj)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 241, in <lambda>
    return lambda obj: outfunc(obj, indexers)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 185, in outfunc
    k1, v1, result = consume_from_indexer(idxr(obj))
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 122, in consume_from_indexer
    a, b = next(idxr)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 145, in outfunc
    yield ii, x[k]
KeyError: 0

======================================================================
FAIL: test_projection_arr_parens_then_idx (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1448, in test_projection_arr_parens_then_idx
    self.assertEqual(search("(@[:]{@.foo, @.bar})[1]", [{'foo': 1, 'bar': 3}, {'foo': 2, 'bar': 1}]), [2, 1])
AssertionError: {'foo': 2, 'bar': 1} != [2, 1]

======================================================================
FAIL: test_projection_obj_parens_then_dot (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1454, in test_projection_obj_parens_then_dot
    self.assertEqual(search("(@{foo: @[0], bar: @[1]}).foo", [1,2]), 1)
AssertionError: {} != 1

======================================================================
FAIL: test_search_dot_parens_dot (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1418, in test_search_dot_parens_dot
    self.assertEqual(search('(@.foo).bar', {'foo': {'bar': 1}}), 1)
AssertionError: {} != 1

======================================================================
FAIL: test_search_idx_on_expr_function (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1390, in test_search_idx_on_expr_function
    self.assertEqual(search("sorted(@)[0]", [2, 1]), 1)
AssertionError: 2 != 1

======================================================================
FAIL: test_search_idx_parens_dot (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1421, in test_search_idx_parens_dot
    self.assertEqual(search('(@[0]).a', [{'a': 1, 'b': 2}, {'a': 3, 'b': 4}]), 2)
AssertionError: {} != 2

======================================================================
FAIL: test_search_idx_parens_idx (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1424, in test_search_idx_parens_idx
    self.assertEqual(search('(@[:1])[1:]', [[1,2],[3,4]]), [[2]])
AssertionError: Lists differ: [[3, 4]] != [[2]]

First differing element 0:
[3, 4]
[2]

- [[3, 4]]
+ [[2]]

----------------------------------------------------------------------
Ran 144 tests in 0.038s

FAILED (failures=6, errors=2)